-- =====================================================================
-- Mail pipeline indexes + orphan cleanup
-- =====================================================================
-- Generated by drizzle-kit + manually extended for:
--   • UNIQUE on (account_id, entity_type, entity_id) — required for native
--     ON CONFLICT upsert used by upsertManyByEntityIds.
--   • Orphan stub archival + deletion — rows with no Subject/From/payload
--     were created by a broken code path and waste space.
--
-- Idempotent: safe to re-run.
-- =====================================================================

CREATE UNIQUE INDEX IF NOT EXISTS "idx_corsair_entities_tenant_type_entity"
  ON "corsair_entities" USING btree ("account_id","entity_type","entity_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_corsair_entities_type_created"
  ON "corsair_entities" USING btree ("entity_type","created_at" DESC NULLS LAST);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_corsair_entities_messages_labels"
  ON "corsair_entities" USING gin (("data"->'labelIds'))
  WHERE "corsair_entities"."entity_type" = 'messages';
--> statement-breakpoint

-- Archive orphan stubs to a temp table before deletion (safety net).
-- The temp table is dropped at session end; re-running this migration in
-- a new session will skip the orphans because they've already been deleted.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM "corsair_entities"
    WHERE entity_type = 'messages'
      AND data->>'subject' IS NULL
      AND data->>'from' IS NULL
      AND data->'payload' IS NULL
  ) THEN
    RAISE NOTICE '[mail-pipeline] No orphan stubs found, skipping cleanup';
    RETURN;
  END IF;

  CREATE TEMP TABLE IF NOT EXISTS "_mail_orphan_archive" AS
    SELECT id, account_id, entity_id, entity_type, version, data, created_at, updated_at
    FROM "corsair_entities"
    WHERE entity_type = 'messages'
      AND data->>'subject' IS NULL
      AND data->>'from' IS NULL
      AND data->'payload' IS NULL;

  DECLARE
    archive_count INTEGER;
  BEGIN
    SELECT COUNT(*) INTO archive_count FROM "_mail_orphan_archive";
    RAISE NOTICE '[mail-pipeline] Archived % orphan stubs to _mail_orphan_archive', archive_count;
  END;

  DELETE FROM "corsair_entities"
  WHERE entity_type = 'messages'
    AND data->>'subject' IS NULL
    AND data->>'from' IS NULL
    AND data->'payload' IS NULL;

  RAISE NOTICE '[mail-pipeline] Orphan cleanup complete';
END $$;
--> statement-breakpoint

ANALYZE "corsair_entities";
